#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum combo_events {
    tn_th,
    sn_sh,
    cn_ch,
    fl_ph,
    gm_gh,
    xm_wh,
    COMBO_COUNT
};

const uint16_t PROGMEM tn_th_combo[] = {KC_T, KC_N, COMBO_END};
const uint16_t PROGMEM sn_sh_combo[] = {KC_S, KC_N, COMBO_END};
const uint16_t PROGMEM cn_ch_combo[] = {KC_C, KC_N, COMBO_END};
const uint16_t PROGMEM fl_ph_combo[] = {KC_F, KC_L, COMBO_END};
const uint16_t PROGMEM gm_gh_combo[] = {KC_G, KC_M, COMBO_END};
const uint16_t PROGMEM xm_wh_combo[] = {KC_X, KC_N, COMBO_END};

combo_t key_combos[] = {
    [tn_th] = COMBO_ACTION(tn_th_combo),
    [sn_sh] = COMBO_ACTION(sn_sh_combo),
    [cn_ch] = COMBO_ACTION(cn_ch_combo),
    [fl_ph] = COMBO_ACTION(fl_ph_combo),
    [gm_gh] = COMBO_ACTION(gm_gh_combo),
    [xm_wh] = COMBO_ACTION(xm_wh_combo)
};

// bool process_record_user(uint16_t keycode, keyrecord_t *record) {
//   switch(keycode) {
//     case tn-th:
//       if (pressed) {
//         SEND_STRING("th");
//       }
//       break;
//     case sn-sh:
//       if (pressed) {
//         SEND_STRING("sh");
//       }
//       break;
//     case cn-ch:
//       if (pressed) {
//         SEND_STRING("ch");
//       }
//       break;
//     case fl-ph:
//       if (pressed) {
//         SEND_STRING("ph");
//       }
//       break;
//     case gm-gh:
//       if (pressed) {
//         SEND_STRING("gh");
//       }
//       break;
//     case xm-wh:
//       if (pressed) {
//         SEND_STRING("wh");
//       }
//       break;
//   }
// }

void process_combo_event(uint16_t combo_index, bool pressed) {
  if (pressed) {
    uprintf("Combo index: %d pressed\n", combo_index);
  switch(combo_index) {
    case tn_th:
      if (pressed) {
        SEND_STRING("th");
      }
      break;
    case sn_sh:
      if (pressed) {
        SEND_STRING("sh");
      }
      break;
    case cn_ch:
      if (pressed) {
        SEND_STRING("ch");
      }
      break;
    case fl_ph:
      if (pressed) {
        SEND_STRING("ph");
      }
      break;
    case gm_gh:
      if (pressed) {
        SEND_STRING("gh");
      }
      break;
    case xm_wh:
      if (pressed) {
        SEND_STRING("wh");
      }
      break;
  }
} else {
    uprintf("Combo index: %d released\n", combo_index);
    }
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(KC_W, KC_X, KC_M, KC_G, KC_J, KC_SCLN, KC_DOT, KC_SLSH, KC_DQUO, KC_QUOT, LSFT_T(KC_C), LT(5,KC_S), LT(1,KC_N), LT(3,KC_T), KC_K, KC_COMM, LT(4,KC_A), LT(2,KC_E), LT(6,KC_I), LSFT_T(KC_H), KC_P, LCTL_T(KC_F), LALT_T(KC_L), KC_D, KC_V, KC_MINS, KC_U, LALT_T(KC_O), LCTL_T(KC_Y), KC_B, KC_ESC, KC_R, LT(7,KC_SPC), KC_P1),
	[1] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_WH_U, KC_BTN2, KC_TRNS, KC_TRNS, KC_BTN2, KC_NO, KC_BTN1, KC_TRNS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_L, KC_WH_D, KC_WH_R, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_LGUI, KC_NO, LCTL(KC_LALT), LCA(KC_LSFT), KC_TRNS, KC_HOME, KC_PGDN, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UNDS, KC_PIPE, KC_QUOT, KC_TRNS, KC_CIRC, KC_ASTR, KC_AMPR, KC_NO, KC_TRNS, KC_HASH, KC_TILD, KC_SLSH, KC_DQUO, KC_DLR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MINS, KC_BSLS, KC_GRV, KC_TRNS, RGB_RMOD, KC_TRNS, KC_TRNS, RGB_MOD),
	[4] = LAYOUT_split_3x5_2(KC_TRNS, KC_COLN, KC_LT, KC_GT, KC_SCLN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT, KC_TRNS, KC_NO, KC_EQL, KC_PLUS, KC_PERC, KC_TRNS, KC_EXLM, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD, KC_TRNS, KC_TRNS, KC_VOLU),
	[5] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_TRNS, KC_NO, LCTL(KC_LALT), KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6, KC_F11, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[6] = LAYOUT_split_3x5_2(KC_PSLS, KC_7, KC_8, KC_9, KC_PPLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_4, KC_5, KC_6, KC_PMNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_PAST, KC_1, KC_2, KC_3, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[7] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_COLN, KC_ESC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_TRNS, KC_PERC, KC_SLSH, KC_ENT, KC_BSPC, DF(1), KC_LGUI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_EXLM, KC_TRNS, DF(0), KC_TRNS, RALT_T(KC_COMM), RCTL_T(KC_DOT), QK_BOOT, KC_TRNS, KC_TAB, KC_NO, KC_TRNS)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




